version: "3"

services:

    db-mssql:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "ef66b58b-6ff2-4c78-bcec-6b279312b625"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"

    db-mysql:
        image: "mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "ef66b58b-6ff2-4c78-bcec-6b279312b625"
        ports:
            - "3306:3306"